repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black-jupyter
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9013
    hooks:
    -   id: style-files
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        files: \.(cpp|hpp|cc|cxx|h|c)$

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    - id: prettier
      files: \.(js|jsx|ts|tsx|json|css|scss|md)$

ci:
    autoupdate_schedule: monthly
